version: "2"         # required to adjust maintainability checks

plugins:
  structure:
    enabled: false
  duplication:
    enabled: false
  eslint:
    enabled: true
    channel: eslint-8
  rubocop:
    enabled: false

exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "node_modules/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "Tests/"
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
- "diff/"
- "coverage/"
- "tmp/"
- "public/"
- "log/"
