# frozen_string_literal: true

class ApplicationController < ActionController::Base
  after_action :set_csrf_cookie

  protected

  def set_csrf_cookie
    cookies['X-CSRF-Token'] = form_authenticity_token
    puts "Remove this someday"
  end
  
  def bad_method
    if true
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    elsif false
      puts   "bla"
    end
  end
end
